version: '3'

networks:
  msisdnapp:
    driver: bridge

services:
  project:
    container_name: projectapp
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
      vault:
        condition: service_healthy
    environment:
      APP_PORT: 8080
    ports:
      - 8080:8080
    networks:
      - msisdnapp
  db:
    image: mysql
    container_name: godockerDB
    ports:
      - "3366:3306"
    expose:
      - "3306"
    env_file:
      - ./config/db_config.env
    restart: on-failure
    volumes:
      - "./docker/db-server/init.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - msisdnapp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 20
  vault:
    image: hashicorp/vault
    container_name: vault
    volumes:
      - ./config/vault_config.hcl:/vault/config/config.hcl
      - ./docker/vault-server/vault-init.sh:/docker/vault-init.sh
    restart: on-failure:5
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "/bin/sh" ,"-c", "[ -f /tmp/healthy ]"]
      interval: 2s
      timeout: 2s
      retries: 30
    #command: ./docker/vault-init.sh
    command: server
    ports:
      - "8200:8200"
    networks:
      - msisdnapp