// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robesmi/MSISDNApp/service (interfaces: MSISDNService)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/robesmi/MSISDNApp/model/dto"
	errs "github.com/robesmi/MSISDNApp/model/errs"
)

// MockMSISDNService is a mock of MSISDNService interface.
type MockMSISDNService struct {
	ctrl     *gomock.Controller
	recorder *MockMSISDNServiceMockRecorder
}

// MockMSISDNServiceMockRecorder is the mock recorder for MockMSISDNService.
type MockMSISDNServiceMockRecorder struct {
	mock *MockMSISDNService
}

// NewMockMSISDNService creates a new mock instance.
func NewMockMSISDNService(ctrl *gomock.Controller) *MockMSISDNService {
	mock := &MockMSISDNService{ctrl: ctrl}
	mock.recorder = &MockMSISDNServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMSISDNService) EXPECT() *MockMSISDNServiceMockRecorder {
	return m.recorder
}

// LookupMSISDN mocks base method.
func (m *MockMSISDNService) LookupMSISDN(arg0 uint64) (*dto.NumberLookupResponse, *errs.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupMSISDN", arg0)
	ret0, _ := ret[0].(*dto.NumberLookupResponse)
	ret1, _ := ret[1].(*errs.AppError)
	return ret0, ret1
}

// LookupMSISDN indicates an expected call of LookupMSISDN.
func (mr *MockMSISDNServiceMockRecorder) LookupMSISDN(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupMSISDN", reflect.TypeOf((*MockMSISDNService)(nil).LookupMSISDN), arg0)
}
