// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/robesmi/MSISDNApp/repository (interfaces: MSISDNRepository)

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/robesmi/MSISDNApp/model/dto"
)

// MockMSISDNRepository is a mock of MSISDNRepository interface.
type MockMSISDNRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMSISDNRepositoryMockRecorder
}

// MockMSISDNRepositoryMockRecorder is the mock recorder for MockMSISDNRepository.
type MockMSISDNRepositoryMockRecorder struct {
	mock *MockMSISDNRepository
}

// NewMockMSISDNRepository creates a new mock instance.
func NewMockMSISDNRepository(ctrl *gomock.Controller) *MockMSISDNRepository {
	mock := &MockMSISDNRepository{ctrl: ctrl}
	mock.recorder = &MockMSISDNRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMSISDNRepository) EXPECT() *MockMSISDNRepositoryMockRecorder {
	return m.recorder
}

// LookupCountryCode mocks base method.
func (m *MockMSISDNRepository) LookupCountryCode(arg0 string) (*dto.CountryLookupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupCountryCode", arg0)
	ret0, _ := ret[0].(*dto.CountryLookupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupCountryCode indicates an expected call of LookupCountryCode.
func (mr *MockMSISDNRepositoryMockRecorder) LookupCountryCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupCountryCode", reflect.TypeOf((*MockMSISDNRepository)(nil).LookupCountryCode), arg0)
}

// LookupMobileOperator mocks base method.
func (m *MockMSISDNRepository) LookupMobileOperator(arg0, arg1 string) (*dto.MobileOperatorLookupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupMobileOperator", arg0, arg1)
	ret0, _ := ret[0].(*dto.MobileOperatorLookupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupMobileOperator indicates an expected call of LookupMobileOperator.
func (mr *MockMSISDNRepositoryMockRecorder) LookupMobileOperator(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupMobileOperator", reflect.TypeOf((*MockMSISDNRepository)(nil).LookupMobileOperator), arg0, arg1)
}
